packages:
  - .
allowBuilds:
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - srvx@0.11.13
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - core-js-pure
  - esbuild
  - lefthook
overrides:
  srvx@<0.11.13: ^0.11.13
