export const siteConfig = {
  site: {
    title: 'Visakan Kirubakaran | Software Developer',
    description:
      'Personal portfolio of Visakan Kirubakaran, a dedicated software developer specializing in web development, APIs, and high-quality software engineering.',
    url: 'https://vikiru.vercel.app',
    base: '',
    locale: 'en',
    lastModified: new Date(),
  },
  author: {
    name: 'Visakan Kirubakaran',
    firstName: 'Visakan',
    lastName: 'Kirubakaran',
    alternateName: 'Vis Kirubakaran',
    jobTitle: 'Software Developer',
    portfolioWebsite: 'https://vikiru.vercel.app',
    githubProfile: 'https://github.com/vikiru',
    linkedinProfile: 'https://linkedin.com/in/viskirubakaran',
    universityName: 'Carleton University',
    universityUrl: 'https://carleton.ca/',
    universityLogo: 'https://carleton.ca/favicon.ico',
  },
  project: {
    name: 'Portfolio Website',
    githubRepo: 'https://github.com/vikiru/vikiru.github.io',
    version: '4.0.0',
    programmingLanguage: ['TypeScript', 'React', 'TailwindCSS', 'Vite'],
    license: 'https://opensource.org/licenses/MIT',
    keywords: [
      'Visakan Kirubakaran',
      'Vis Kirubakaran',
      'Full Stack Developer',
      'Software Developer',
      'React',
      'TypeScript',
      'TailwindCSS',
      'ShadCN UI',
      'Vite',
      'Vercel',
      'Portfolio Website',
    ],
  },
  assets: {
    themeColor: '#1e1e24',
  },
};
