export const noterraLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Person',
      '@id': 'https://vikiru.vercel.app/#person',
      name: 'Visakan Kirubakaran',
      alternateName: 'Vis Kirubakaran',
      givenName: 'Visakan',
      familyName: 'Kirubakaran',
      jobTitle: 'Software Developer',
      url: 'https://vikiru.vercel.app',
      sameAs: [
        'https://github.com/vikiru',
        'https://linkedin.com/in/viskirubakaran',
      ],
      alumniOf: {
        '@type': 'EducationalOrganization',
        name: 'Carleton University',
        url: 'https://carleton.ca/',
        logo: 'https://carleton.ca/favicon.ico',
      },
    },
    {
      '@type': 'SoftwareSourceCode',
      '@id': 'https://github.com/vikiru/noterra/#software',
      name: 'noterra',
      description:
        'AI-powered learning tool to generate comprehensive notes and flashcards | TypeScript, Next.js, Gemini, PostgreSQL, Drizzle',
      url: 'https://github.com/vikiru/noterra',
      author: { '@id': 'https://vikiru.vercel.app/#person' },
      maintainer: { '@id': 'https://vikiru.vercel.app/#person' },
      keywords: [
        'nextjs',
        'gemini',
        'typescript',
        'postgresql',
        'drizzle',
        'tiptap',
        'clerk',
        'mermaid',
      ],
      version: '1.0.0',
      programmingLanguage: 'TypeScript',
      license: 'https://opensource.org/licenses/MIT',
      dateCreated: '2025-01-01T00:00:00.000Z',
      dateModified: '2026-01-28T00:00:00.000Z',
      codeRepository: 'https://github.com/vikiru/noterra',
      runtimePlatform: ['Node.js', 'Web', 'Browser'],
    },
    {
      '@type': 'WebSite',
      '@id': 'https://vikiru.github.io/noterra/#homepage',
      name: 'Noterra Documentation',
      description:
        'Documentation for Noterra - AI-powered learning tool to generate comprehensive notes and flashcards using Gemini AI, Next.js, and PostgreSQL.',
      url: 'https://vikiru.github.io/noterra/',
      creator: { '@id': 'https://vikiru.vercel.app/#person' },
      license: 'https://opensource.org/licenses/MIT',
      inLanguage: 'en',
      dateModified: '2026-01-28T00:00:00.000Z',
      about: { '@id': 'https://github.com/vikiru/noterra/#software' },
      sameAs: ['https://github.com/vikiru/noterra'],
      mainEntity: { '@id': 'https://github.com/vikiru/noterra/#software' },
      mainEntityOfPage: 'https://vikiru.github.io/noterra/',
    },
  ],
};
