export const parseumLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Person',
      '@id': 'https://vikiru.vercel.app/#person',
      name: 'Visakan Kirubakaran',
      alternateName: 'Vis Kirubakaran',
      givenName: 'Visakan',
      familyName: 'Kirubakaran',
      jobTitle: 'Software Developer',
      url: 'https://vikiru.vercel.app',
      sameAs: [
        'https://github.com/vikiru',
        'https://linkedin.com/in/viskirubakaran',
      ],
      alumniOf: {
        '@type': 'EducationalOrganization',
        name: 'Carleton University',
        url: 'https://carleton.ca/',
        logo: 'https://carleton.ca/favicon.ico',
      },
    },
    {
      '@type': 'SoftwareSourceCode',
      '@id': 'https://github.com/vikiru/parseum/#software',
      name: 'Parseum',
      description:
        'A markdown to HTML parser and editor built using Peggy.js, React, TailwindCSS and DaisyUI.',
      url: 'https://github.com/vikiru/parseum',
      author: { '@id': 'https://vikiru.vercel.app/#person' },
      maintainer: { '@id': 'https://vikiru.vercel.app/#person' },
      keywords: [
        'markdown',
        'html',
        'parser',
        'editor',
        'peggy.js',
        'react',
        'tailwindcss',
        'daisyui',
      ],
      version: '1.0.0',
      programmingLanguage: 'JavaScript',
      license: 'https://opensource.org/licenses/MIT',
      dateCreated: '2024-02-01T00:00:00.000Z',
      dateModified: '2024-03-31T00:00:00.000Z',
      codeRepository: 'https://github.com/vikiru/parseum',
      runtimePlatform: ['Node.js', 'Web', 'Browser'],
      targetProduct: { '@id': 'https://parseum.surge.sh/#web-app' },
    },
    {
      '@type': 'WebApplication',
      '@id': 'https://parseum.surge.sh/#web-app',
      name: 'Parseum',
      description:
        'A markdown to HTML parser and editor built using Peggy.js, React, TailwindCSS and DaisyUI.',
      url: 'https://parseum.surge.sh',
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'Web',
      browserRequirements: 'Requires JavaScript and a modern web browser',
      softwareVersion: '1.0.0',
      copyrightHolder: { '@id': 'https://vikiru.vercel.app/#person' },
      copyrightNotice:
        'Copyright 2024 Visakan Kirubakaran. All rights reserved.',
      copyrightYear: 2024,
      mainEntity: { '@id': 'https://github.com/vikiru/parseum/#software' },
      mainEntityOfPage: 'https://parseum.surge.sh',
    },
    {
      '@type': 'WebSite',
      '@id': 'https://vikiru.github.io/parseum/#homepage',
      name: 'Parseum Documentation',
      alternateName: 'Parseum',
      description:
        'Documentation for Parseum - A markdown to HTML parser and editor built using Peggy.js, React, TailwindCSS and DaisyUI.',
      url: 'https://vikiru.github.io/parseum/',
      creator: { '@id': 'https://vikiru.vercel.app/#person' },
      license: 'https://opensource.org/licenses/MIT',
      inLanguage: 'en',
      dateModified: '2026-01-12T07:02:47.085Z',
      image: 'https://vikiru.github.io/parseum/logo.png',
      about: { '@id': 'https://github.com/vikiru/parseum/#software' },
      sameAs: ['https://github.com/vikiru/parseum', 'https://parseum.surge.sh'],
      mainEntity: { '@id': 'https://github.com/vikiru/parseum/#software' },
      mainEntityOfPage: 'https://vikiru.github.io/parseum/',
    },
  ],
};
