export const restasaurusLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Person',
      '@id': 'https://vikiru.vercel.app/#person',
      name: 'Visakan Kirubakaran',
      alternateName: 'Vis Kirubakaran',
      givenName: 'Visakan',
      familyName: 'Kirubakaran',
      jobTitle: 'Software Developer',
      url: 'https://vikiru.vercel.app',
      sameAs: [
        'https://github.com/vikiru',
        'https://linkedin.com/in/viskirubakaran',
      ],
      alumniOf: {
        '@type': 'EducationalOrganization',
        name: 'Carleton University',
        url: 'https://carleton.ca/',
        logo: 'https://carleton.ca/favicon.ico',
      },
    },
    {
      '@type': 'SoftwareSourceCode',
      '@id': 'https://github.com/vikiru/restasaurus/#software',
      name: 'RESTasaurus',
      description:
        'A dinosaur REST API built using Express, MongoDB and Mongoose with comprehensive data for almost 1200 dinosaurs.',
      url: 'https://github.com/vikiru/restasaurus',
      author: { '@id': 'https://vikiru.vercel.app/#person' },
      maintainer: { '@id': 'https://vikiru.vercel.app/#person' },
      keywords: [
        'restasaurus',
        'rest',
        'api',
        'mongodb',
        'mongoose',
        'express',
        'dinosaurs',
      ],
      version: '1.0.1',
      programmingLanguage: 'JavaScript',
      license: 'https://opensource.org/licenses/MIT',
      dateCreated: '2024-01-07T00:00:00.000Z',
      dateModified: '2024-02-01T00:00:00.000Z',
      codeRepository: 'https://github.com/vikiru/restasaurus',
      runtimePlatform: 'Node.js',
    },
    {
      '@type': 'WebAPI',
      '@id': 'https://restasaurus.onrender.com/api/v1/#api',
      name: 'RESTasaurus API',
      description:
        'A dinosaur REST API built using Express, MongoDB and Mongoose with comprehensive data for almost 1200 dinosaurs.',
      url: 'https://restasaurus.onrender.com/api/v1',
      documentation: 'https://vikiru.github.io/restasaurus',
      provider: { '@id': 'https://vikiru.vercel.app/#person' },
      termsOfService: 'https://vikiru.github.io/restasaurus/terms',
    },
    {
      '@type': 'WebSite',
      '@id': 'https://vikiru.github.io/restasaurus/#homepage',
      name: 'RESTasaurus Documentation',
      alternateName: 'RESTasaurus',
      description:
        'Documentation for RESTasaurus - A dinosaur REST API built using Express, MongoDB and Mongoose with comprehensive data for almost 1200 dinosaurs.',
      url: 'https://vikiru.github.io/restasaurus/',
      creator: { '@id': 'https://vikiru.vercel.app/#person' },
      license: 'https://opensource.org/licenses/MIT',
      inLanguage: 'en',
      dateModified: '2026-01-13T19:57:04.787Z',
      image: 'https://vikiru.github.io/restasaurus/logo.png',
      about: { '@id': 'https://github.com/vikiru/restasaurus/#software' },
      sameAs: [
        'https://github.com/vikiru/restasaurus',
        'https://restasaurus.onrender.com/api/v1',
      ],
      mainEntity: { '@id': 'https://github.com/vikiru/restasaurus/#software' },
      mainEntityOfPage: 'https://vikiru.github.io/restasaurus/',
    },
  ],
};
